---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=8.1.0"
  "juniper.device": ">=2.0.0"
license_file: LICENSE
name: junos
namespace: junipernetworks
description: Ansible Network Collection for Junipernetworks Junos devices.
readme: README.md
repository: https://github.com/Juniper/ansible-junos-stdlib
issues: https://github.com/Juniper/ansible-junos-stdlib/issues
tags: [juniper, junipernetworks, junos, networking, security, netconf]
version: 11.0.0
